apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-k8s
  template:
    metadata:
      labels:
        app: demo-k8s
    spec:
      containers:
      - name: demo-k8s-app
        image: xuzhang037/demo-k8s-app:latest
        ports:
        - containerPort: 80
      - name: demo-k8s-worker
        image: xuzhang037/demo-k8s-worker:latest
        ports:
          - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: demo-k8s
spec:
  selector:
    app: demo-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
