apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-k8s
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo-k8s
  template:
    metadata:
      labels:
        app: demo-k8s
    spec:
      containers:
      - name: demo-k8s
        image: xuzhang037/demo-k8s
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: demo-k8s
spec:
  selector:
    app: demo-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
